package share.cards.effects;

public enum Effect {
   /* 3LUNAR_PLUS_3GOLD,
    BUY_4GLORY_FOR_3GOLDS,
    CHOOSE_GOLD_LUNAR_SOLAR
*/
   initHammer,
   increaseResLimit,
   throw1dice,
   noaction,
   steal2,
   boarForge,
   tokenCerberus,
   side3x,
   fullThrow,
   fullThrow2Transform,
   goldToVP,
   G3M,
   choose1GMF,
   sideShip,
   loosThrow,
   shieldForge,
   tokenTriton,
   sideMirror,
   Throws,
   ThrowsTransform,
   scoreForgedSides,
   nympheReinforcement,
   diceSwap,
   none,
   initScepter,
   initCompanion,
   throwAllChooseResources,
   throwCelestialDie,
   forgeVP,
   stealLessGold,
   stealFireMoon,
   convertGoldToVP,
   treeEffect,
   forge4G,
   upgradeSide,
   copySide,
   countFeats,
   countVP,
   forgeEverywhere,
   gainTurn,
   oustAll,
   sideMoonGolem,
   greatGolem,
   sideSunGolem,
   timeGolem,
   memoryTokens,
   sideShieldRebellion,
   sideDogged,
   sideMisfortune,

   Effect(){

   }
}
